### PR TITLE
Attempt to fix generated Swift code for deserializing optional associated types in enum variants

### LINKED ISSUE #77: Deserialization fails in Swift for enums containing optional values
Suppose we have an enum with a variant containing an optional value:
```rust
#[typeshare]
#[derive(Serialize, Deserialize)]
#[serde(tag = "type", content = "content")]
pub enum AlgebraicEnumWithOptionalValue {
  Variant(Option<()>)
}
```

The code to deserialize this variant will look like this:
```
			case .variant:
				if let content = try? container.decode(AlgebraicEnumWithOptionalValue?.self, forKey: .content) {
					self = .variant(content)
					return
				}
```

However, if `content` is null (i.e. the variant on the Rust side contained `None`), this will fail to deserialize with error 1002.

### PR DESCRIPTION
**Pull request by InquisitivePenguin**
Fixes #77, see the issue for details.

### CODE REVIEW

File: core/src/language/swift.rs [hunk 1]
```diff
@@ -529,12 +530,17 @@ impl Swift {
                                 "
 			case .{case_name}:
 				if let content = try? container.decode({case_type}.self, forKey: .{content_key}) {{
```
Comment (kevinbhayes) [inline core/src/language/swift.rs:532]: I believe this will fail if content is null. I think we need an else if case to capture that.

```
			case .{case_name}:
				if let content = try? container.decode({case_types}.self, forKey: .content) {
					self = .{case_name}(content)
					return
				}
				else if let isNil = try? container.decodeNil(forKey: .content), isNil {
					self = .{case_name}(nil)
					return
				} 

```

**Review by kevinbhayes — CHANGES_REQUESTED** [review]

File: core/src/language/swift.rs (hunk 1 above)
Comment (InquisitivePenguin) [reply core/src/language/swift.rs:549]: Should be fixed in the latest commit.

**Review by CerulanLumina — APPROVED** [review]
